export interface Category {
    id: number;
    label: string;
  }
  
  export interface Produit {

    images: any;
    ref: any;
    stock: any;
    etat: any;
    description: any;
    marque: any;
    id: number; // Optional because it's auto-generated by the backend
    name: string;
    type: string;
    Prix: number;
    category: Category;
  }